solax:
  modbus:
    # Modbus TCP connection
    host: 192.168.0.31
    port: 502
    # Time management required for modbus
    time:
      # Delay between two requests
      delay: 1000
  # ID of the inverter in modbus, can differ if you have multiple inverters
  unitId: 1
  # Advanced password for the inverter
  password: 2014

# API for electricity prices provided to grid
# - Documentation: https://spotovaelektrina.cz/api
ote:
  api:
    url: "https://spotovaelektrina.cz/api/"

# API for weather data
# - Documentation: https://www.meteosource.com/documentation
meteosource:
  api:
    url: "https://www.meteosource.com/api/"
    key: "YOUR_API_KEY"
  # Location for weather data. Lat and lon is always better. How to find is described in the documentation
  location:
    placeId: "prague"
    # Coordinates for the location
    lat: 50.0755
    lon: 14.4378

automation:
  export:
    power:
      min: 100
      max: 3950
    minPrice: 0.5
  weather:
    threshold:
      cloudy: 5
      thunderstorm: 10
    thunderstormHourForecast: 2

# Logging configuration
logging:
  config: classpath:log4j2.xml